# Generated by Django 3.0.3 on 2020-02-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название кафедры', max_length=300, verbose_name='Название кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Факультет', max_length=300, verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Факультет',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Введите номер группы', max_length=4, verbose_name='Номер группы')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_part.Department')),
            ],
            options={
                'verbose_name': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Имя', max_length=150, verbose_name='Имя')),
                ('lastName', models.CharField(help_text='Фамилия', max_length=150, verbose_name='Фамилия')),
                ('middleName', models.CharField(blank=True, help_text='Отчество (если есть)', max_length=150, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True, verbose_name='Email')),
                ('teacherPhoto', models.ImageField(blank=True, null=True, upload_to='media/profiles/teacher_profile_pics')),
                ('teacherPhoneNumber', models.IntegerField(blank=True, help_text='Номер телефона предподавателя', null=True, verbose_name='Номер телефона преподавателя')),
                ('departments', models.ManyToManyField(help_text='Кафедры', to='core_part.Department', verbose_name='Кафедры')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Имя', max_length=150, verbose_name='Имя')),
                ('lastName', models.CharField(help_text='Фамилия', max_length=150, verbose_name='Фамилия')),
                ('middleName', models.CharField(blank=True, help_text='Отчество (если есть)', max_length=150, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True, verbose_name='Email')),
                ('studentPhoto', models.ImageField(blank=True, null=True, upload_to='media/profiles/student_profile_pics')),
                ('ticketNumber', models.CharField(max_length=20)),
                ('studentGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_part.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(blank=True, help_text='Староста группы', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_part.Student', verbose_name='Староста'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название дисциплины', max_length=300, verbose_name='Название дисциплины')),
                ('groups', models.ManyToManyField(help_text='Группы с этой дисциплиной', to='core_part.Group', verbose_name='Группы')),
                ('teachers', models.ManyToManyField(help_text='Преподаватели с этой дисциплиной', to='core_part.Teacher', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Дисциплина',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_part.Faculty'),
        ),
    ]
